console.log("Hello", "string"  )
console.log(true, "boolean"  )
console.log("Name", "string"  )
console.log(33, "number"  )
console.log("90", "string"  )
console.log(90+"77", "string"  )
console.log( {name:'Anu', age:15}, "object")
console.log(false, "boolean"  )
console.log(1655/5, "number" )
console.log(["javascript", "html", "css"], "array")