let bornYear = 1995
let bornMonth = 11
let bornDay = 28
let nowyear = 2024
let nowMonth = 7
let nowday = 20
let a = 12
let b = 31
let g = 365 
Console.log amdirsanday = (nowyear - bornYear)*g + ((a - bornMonth) + nowMonth ) * b + (b - bornDay + nowday ) - g + b